#!/bin/bash
echo chargement de la génération
echo "set terminal png" > GrapheGener
echo "set output 'file.png'" >> GrapheGener

echo "set boxwidth 0.5" >> GrapheGener
echo "set style fill solid" >> GrapheGener
echo "set ylabel 'Octets'" >> GrapheGener
echo "set xlabel 'Ip'" >> GrapheGener
echo "set xtics rotate by -45" >> GrapheGener
echo "set title 'Sujet 4'" >> GrapheGener

echo -e "Génération du graphique en cours veuillez patientez... \n"
echo "plot 'donneGnop' using 1:3:xtic(2) with boxes ls 1 title 'Consommation'" >> GrapheGener

gnuplot GrapheGener
rm GrapheGener

